title: "OSCAR and JuliaLang Reading Group"
description: "University of Leeds â€” notes, updates, and FAQ"
theme: minima
markdown: kramdown

header_pages:
  - index.md
  - notes/index.md
  - faq/index.md
